# -*- mode: ruby -*-
# vi: set ft=ruby :


nodes = [
#  { :hostname => 'vagrant-test', :box => 'ubuntu-14-04-x64' },
  { :hostname => 'appserver', :box => 'ubuntu-14-04-x64' },
  { :hostname => 'dbserver', :box => 'ubuntu-14-04-x64' },
]

Vagrant.configure("2") do |config|


  config.vm.provider :digital_ocean do |provider, override|
    override.ssh.private_key_path = '~/.ssh/id_rsa'
    override.vm.box = 'digital_ocean'
    override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"

    provider.token = '92b5fe70d684ff1a0d14cd4a7110d7e843444aea8068e7db36530f95d8e17eef'  # Remember to remove before committing! Use an environment variable instead.
    provider.image = 'ubuntu-14-04-x64'
    provider.region = 'nyc1'
    provider.size = '512mb'
    provider.setup = false
  end

#  config.puppet_install.puppet_version = :latest
#  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
     nodeconfig.vm.box = node[:box]
     nodeconfig.vm.hostname = node[:hostname]
     nodeconfig.vm.synced_folder ".", "/vagrant", type: "rsync"
     nodeconfig.vm.provision :shell, :path => "./bootstrap.sh"




     nodeconfig.vm.provision :puppet do |puppet|
       puppet.module_path= "./module_path"
       puppet.manifests_path = "./environments_path/manifests"
       puppet.synced_folder_type = "rsync"
     end

      if node[:hostname] == 'dbserver' then
        nodeconfig.vm.provision "shell", path: "./installMySQL.sh"
      end



# Här börjar SMB kaxa, den kaxar även utan puppet_install
#     nodeconfig.puppet_install.puppet_version = :latest
#     nodeconfig.vm.provision :puppet do |puppet|
#       puppet.module_path= "./module_path"
#       puppet.manifests_path = "./environments_path/manifests"
#      end
   end



 end

#  config.puppet_install.puppet_version = :latest
#  config.vm.synced_folder ".", "/vagrant", type: "rsync", disable: true

#    nodes.each do |node|
#    	config.vm.define node[:hostname] do |nodeconfig|
#    	 nodeconfig.vm.box = node[:box]
#    	 nodeconfig.vm.hostname = node[:hostname]

#      nodeconfig.vm.provider :digital_ocean do |provider, override|
#        override.ssh.private_key_path = '~/.ssh/id_rsa'
#        override.vm.box = 'digital_ocean'
#        override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
        #override.nfs.functional = false

#        provider.token = '92b5fe70d684ff1a0d14cd4a7110d7e843444aea8068e7db36530f95d8e17eef'  # Remember to remove before committing! Use an environment variable instead.
#        provider.image = 'ubuntu-14-04-x64'
#        provider.region = 'nyc1'
#        provider.size = '512mb'
#        provider.setup = false
#    end

    #nodeconfig.vm.synced_folder ".", "/vagrant", type: "rsync"


#    nodeconfig.vm.provision :puppet do |puppet|
#      puppet.module_path= "./module_path"
#      puppet.manifests_path = "./environments_path/manifests"
#    end


#   end

#end

#config.vm.hostname = 'vagrant-test'

#config.vm.provider :digital_ocean do |provider, override|
#  override.ssh.private_key_path = '~/.ssh/id_rsa'
#  override.vm.box = 'digital_ocean'
#  override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"

#  provider.token = '92b5fe70d684ff1a0d14cd4a7110d7e843444aea8068e7db36530f95d8e17eef'  # Remember to remove before committing! Use an environment variable instead.
#  provider.image = 'ubuntu-14-04-x64'
#  provider.region = 'nyc1'
#  provider.size = '512mb'
#  provider.setup = false
#end

#config.vm.synced_folder ".", "/vagrant", type: "rsync"


end
